# Generated by Django 5.2.7 on 2025-10-23 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=100)),
                ("team", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=10)),
                ("height", models.FloatField(null=True)),
                ("weight", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pass",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("action_type", models.CharField(max_length=50)),
                ("completed_pass", models.BooleanField()),
                ("potential_assist", models.BooleanField()),
                ("turnover", models.BooleanField()),
                ("ball_start_loc_x", models.FloatField()),
                ("ball_start_loc_y", models.FloatField()),
                ("ball_end_loc_x", models.FloatField()),
                ("ball_end_loc_y", models.FloatField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shot",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("action_type", models.CharField(max_length=50)),
                ("shot_made", models.BooleanField()),
                ("points", models.IntegerField()),
                ("loc_x", models.FloatField()),
                ("loc_y", models.FloatField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Turnover",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("action_type", models.CharField(max_length=50)),
                ("loc_x", models.FloatField()),
                ("loc_y", models.FloatField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.player"
                    ),
                ),
            ],
        ),
    ]
